# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ct6uggFru8AwPdmv3znBK05aYbzT-uF
"""

import streamlit as st
import requests

# MET API를 이용해 작품 검색
def search_artworks(query):
    search_url = "https://collectionapi.metmuseum.org/public/collection/v1/search"
    params = {"q": query}
    res = requests.get(search_url, params=params).json()
    return res.get("objectIDs", [])[:5]  # 상위 5개만

# 작품 상세 정보 가져오기
def get_artwork_details(object_id):
    obj_url = f"https://collectionapi.metmuseum.org/public/collection/v1/objects/{object_id}"
    return requests.get(obj_url).json()

# Streamlit UI 구성
st.title("🖼️ MET Museum Artwork Explorer")

query = st.text_input("🔎 Search for artworks (e.g., Monet, armor, cat):")

if query:
    st.write("검색 중...")
    ids = search_artworks(query)
    if not ids:
        st.warning("검색 결과가 없습니다.")
    else:
        for oid in ids:
            data = get_artwork_details(oid)
            st.subheader(data.get("title", "Untitled"))
            st.image(data.get("primaryImageSmall"), width=300)
            st.caption(f"작가: {data.get('artistDisplayName', '알 수 없음')}, 연도: {data.get('objectDate', '-')}")